@baseAddress = http://localhost:5022
@categoryId=08de1bad-47c3-0a30-3473-5af664580000
@courseId=08de1bad-0b1d-c06e-3473-5af664580000
@userId=64580000-5af6-3473-8d80-08de1bad0b1d

GET {{baseAddress}}/api/v1/categories
Accept: application/json
###
Post {{baseAddress}}/api/v1/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1"
}
###
GET {{baseAddress}}/api/v1/categories/{{categoryId}}
Accept: application/json
###
POST {{baseAddress}}/api/v1/courses
Accept: application/json
Content-Type: application/json

{
  "name": "New Course 1",
  "description": "This is a new course",
  "price": 99.99,
  "categoryId": "{{categoryId}}"
}
###
PUT {{baseAddress}}/api/v1/courses
Accept: application/json
Content-Type: application/json

{
  "Id": "{{courseId}}",
  "name": "New Course 33",
  "description": "This is a new course 33",
  "price": 199.99,
  "categoryId": "{{categoryId}}"
}
###
###
GET {{baseAddress}}/api/v1/courses
Accept: application/json
###
GET {{baseAddress}}/api/v1/courses/{{courseId}}
Accept: application/json
###
Delete {{baseAddress}}/api/v1/courses/{{courseId}}
Accept: application/json
###
Get {{baseAddress}}/api/v1/courses/user/{{userId}}
Accept: application/json
###