@baseAddress = http://localhost:5022
@categoryId=08de18a0-3412-c8ec-3473-5af664580000
GET {{baseAddress}}/api/categories
Accept: application/json

###
Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1"
}

###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json